### ISSUE TITLE
Issue creating batch or users

### ISSUE THREAD

**Issue by djcbhatia** [imperialsoftech/coffee-supplychain-ethereum#6] opened 2018-09-24 02:53 UTC
For the setup, am using development ganache, with chrome metamask not rinkeby 

Got the DAPP compiled and migrated, setup the app.js with the addresses from the migration, and designated metamask address 1 as the admin address.
However from the admin UI, am not able to create a batch or define a user.  even before I can click on submit in metamask, get a transaction error, error thrown in contract code.  

![11_1_add_batch_error_2](https://user-images.githubusercontent.com/43528920/45936363-76d39980-bf83-11e8-9653-62e5df3c9143.PNG)

Please provide guidance - thank you

**Comment by imperialsoftech** [comment] 2018-09-25 03:45
Duplicate of #5

**Comment by imperialsoftech** [comment] 2018-09-25 03:46
Duplicate of #5

**Closed by imperialsoftech** 2018-09-25 03:46 UTC
